### ISSUE TITLE
Dto 로직분리

### ISSUE THREAD

**Issue by again7536** [phdljr/BoardProject#14]
단일 책임 원칙에 따라 Dto에는 원칙적으로는 비즈니스 로직이 첨가되어서는 안될 것 같음

`src/main/java/kr/ac/project/boardproject/dto/response/BoardListResponseDto.java` 코드를 보면 로직이 포함됨
게다가 해당 DTO가 사용되는 곳이 BoardService 하나 밖에 없으므로 로직 분리가 필요할듯

```java
@Getter
@Setter
public class BoardListResponseDto {
    private int totalPageNumber;
    private int currentPageNumber;
    private boolean previousPage;
    private boolean nextPage;
    private List<Integer> pageList;
    private List<BoardResponseDto> boardList;

    public BoardListResponseDto(Page<Board> page) {
        makePageList(page);
    }

    private void makePageList(Page<Board> page) {
        int pageSize = page.getSize();

        totalPageNumber = page.getTotalPages();
        currentPageNumber = page.getNumber() + 1;
        boardList = makeBoardListDto(page);

        int tempEnd = (int)Math.ceil(currentPageNumber / (float)pageSize) * pageSize; // 23페이지라면 20페이지로 맞춰주기
        int start = tempEnd - (pageSize - 1);
        int end = Math.min(totalPageNumber, tempEnd);
        previousPage = start > 1;
        nextPage = totalPageNumber > tempEnd;
        pageList = IntStream.rangeClosed(start, end).boxed().collect(Collectors.toList());
    }

    private List<BoardResponseDto> makeBoardListDto(Page<Board> page) {
        return boardList = page.getContent().stream().map(board ->
                BoardResponseDto.builder()
                        .id(board.getId())
                        .title(board.getTitle())
                        .nickname(board.getMember().getNickname())
                        .registerDate(board.getRegisterDate())
                        .hit(board.getHit())
                        .build()
        ).collect(Collectors.toList());
    }
}
```

**Comment by phdljr** [comment]
"DTO does not have any behavior **except for storage, retrieval, serialization and deserialization of its own data** ([mutators](https://en.wikipedia.org/wiki/Mutator_method), [accessors](https://en.wikipedia.org/wiki/Method_(computer_programming)), [parsers](https://en.wikipedia.org/wiki/Parsing) and [serializers](https://en.wikipedia.org/wiki/Serialization))." - [위키백과](https://en.wikipedia.org/wiki/Data_transfer_object)

자료를 찾아보니, DTO에는 비즈니스 로직이 있으면 안된다지만 데이터를 변환해주는 로직은 들어가도 되는 것 같아보임.
특히 페이지네이션 관련 로직은 해당 DTO에서만 쓰이는거라 나는 DTO에 있는게 더 깔끔하고 낫다는 생각이 드는데, 어떰?

**Comment by again7536** [comment]
>"DTO does not have any behavior except for storage, retrieval, serialization and deserialization of its own data ([mutators](https://en.wikipedia.org/wiki/Mutator_method), [accessors](https://en.wikipedia.org/wiki/Method_(computer_programming)), [parsers](https://en.wikipedia.org/wiki/Parsing) and [serializers](https://en.wikipedia.org/wiki/Serialization))." - [위키백과](https://en.wikipedia.org/wiki/Data_transfer_object)
자료를 찾아보니, DTO에는 비즈니스 로직이 있으면 안된다지만 데이터를 변환해주는 로직은 들어가도 되는 것 같아보임.
특히 페이지네이션 관련 로직은 해당 DTO에서만 쓰이는거라 나는 DTO에 있는게 더 깔끔하고 낫다는 생각이 드는데, 어떰?

코멘트보고 다시보니까 비즈니스 로직은 없어서 DTO에 해당 코드가 있는게 맞는 것 같다!!
왜 비즈니스 로직이라고 생각했는지 의문이네...

그런데 해당 DTO가 가진 책임이 조금 과한거는 맞는거 같다고 생각해
그래서 몇가지 다시 생각해봤는데
1. 생성자에서 `Page`를 인자로 받지 말고 아래처럼 각각 받기
Page를 다 넘기면 테스트 용이성이 떨어질 수 있다고 생각해
(DTO를 굳이 테스트할 일이 있겠냐만은 그래도)
```java
public BoardListResponseDto(List<Board> boardList, int totalPage, int size, int currentNumber)
```
2. Board -> BoardResponseDto 변환 로직을 Board나 BoardResponseDto에 넣기
BoardListResponseDto가 변환하고 있는거는 조금 이상하다고 느껴지네
이렇게 하면 코드가 좀 더 깔끔해지고 책임이 분산될 수 있을듯

3. 클래스 전체 `@Setter` 제거하기
이거 강의 들으면서 좀 느낀건데 DTO나 Entity는 Setter가 최대한 없는게 맞는거 같다
필요한 Setter만 명시하는게 맞는듯

**Comment by phdljr** [comment]
### 1. `public BoardListResponseDto(List<Board> boardList, int totalPage, int size, int currentNumber)`

확실히 한번에 넘기기보단, 이렇게 분해해서 넘겨주면 **테스트할 때 훨씬 편할 것 같다!**

### 2. Board -> BoardResponseDto 변환 로직을 Board나 BoardResponseDto에 넣기

지금보니, 구조가 조금 이상한 것 같네.
게시글 목록 조회랑 게시글 조회를 따로 생각해서 그런지 뭔가 엉킨 느낌이 드네.

변환 로직을 Board나 BoardResponseDto에 넣는게 훨씬 더 나을 거 같다!

나는 개인적으로 **Entity에는 DB에 영향을 주는 코드만을 적어주는게 나아 보여서,**
**DTO에 넣어두면 어떨까** 싶은데, 어때?

### 3. 클래스 전체 @Setter 제거하기

Entity에는 없애는게 맞다고 생각했는데, **DTO도 제거하는게 맞는 것 같아.**

실제로 개발하면서 DTO에 setter를 사용한 적이 잘 없는 것 같아.
하물며, **데이터가 변경될 위험도 줄어드니** 확실히 제거하는게 맞는 것 같다!

**Comment by again7536** [comment]
## 개발 내용
- [x] #16, #17 해결되면 아래 문제 해결하기

> 1. 생성자에서 Page를 인자로 받지 말고 아래처럼 각각 받기
Page를 다 넘기면 테스트 용이성이 떨어질 수 있다고 생각해
(DTO를 굳이 테스트할 일이 있겠냐만은 그래도)
