### ISSUE TITLE
DTO Setter 제거

### ISSUE THREAD

**Issue by again7536** [phdljr/BoardProject#16]
## 개발 내용
- [x] 클래스 전체 setter 제거하기

>### 3. 클래스 전체 @Setter 제거하기
Entity에는 없애는게 맞다고 생각했는데, **DTO도 제거하는게 맞는 것 같아.**
실제로 개발하면서 DTO에 setter를 사용한 적이 잘 없는 것 같아.
하물며, **데이터가 변경될 위험도 줄어드니** 확실히 제거하는게 맞는 것 같다!
_Originally posted by @phdljr in https://github.com/phdljr/BoardProject/issues/14#issuecomment-1409855685_

**Comment by phdljr** [comment]
@Monacobbb 

Reflection API는 쉽게 말하자면,

런타임시에 해당 클래스나 객체의 정보를 읽어내서 값을 수정할 수 있는 기술인거 같아.
특히, Proxy Pattern이나 스프링의 AOP를 구현할때도 내부적으로 쓰이는 기술 중 하나로 알고있어.
신기하게도, getter나 setter 없이도 가능하고 심지어 private 접근 지정자인 필드에 접근해서 값을 넣어줄 수 있어.

(이건 내가 한참 Reflection API에 관심있어서 찾아본 영상 중 하나인데, 나름 신기했음
스프링의 @AutoWired 기능을 Reflection API로 구현한 영상 - https://youtu.be/67YdHbPZJn4?t=722)

결론은 DTO에 기본 생성자와 getter만 넣어두면 된다는 말인거 같은데,
나도 잠깐 조사해보니 위에서 말한 1, 2번 말이 그대로 나오는거 같네.
[(조사 링크)](https://velog.io/@conatuseus/RequestBody%EC%97%90-%EC%99%9C-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC%84%B1%EC%9E%90%EB%8A%94-%ED%95%84%EC%9A%94%ED%95%98%EA%B3%A0-Setter%EB%8A%94-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-3-idnrafiw)

setter를 붙이는 것보단 getter를 사용함으로써 값의 변경 위험도를 줄일 수 있어서 **getter를 사용하는게 나아보이고**,
기본 생성자는 필수이므로 @NoArgsConstructor를 붙여줘야 하나보네.

아주 유익한 정보였다!
